"""ExecutionMetadata — design §4 + Phase 3 commit 3.

Single dataclass that captures one ResilientExecutor.execute() run for
RL mirror + outbound webhook payload + log structured-key shape.

  - ``from_execution_result(...)`` — class constructor that pulls
    everything off ``ExecutionResult`` plus the executor's bookkeeping
    (retry / fallback decision lists, parent_task_id).
  - ``to_rl_experience_state()`` — produces the dict that lands in
    ``RLExperience.state`` (and feeds the embedded state_text).
  - ``to_rl_experience_action()`` — produces the dict that lands in
    ``RLExperience.action`` (final_platform / chain / actionable_hint).
  - ``to_webhook_payload(event_type)`` — produces the JSON-able payload
    for outbound webhook events. Truncates ``stdout_summary`` /
    ``stderr_summary`` to **512 bytes** for non-``failed`` events
    (design §11.3 + plan §2.4) — failed events get the full 4KB redacted
    summary so subscribers can drive on-call.

Stable wire shape — keep additive. Renames require coordinating with
the RL writer + webhook subscribers. Embeddings of the state text are
generated by the RL service, not here.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional

from .adapters.base import ExecutionResult
from .policy import FallbackDecision
from .status import Status


# Webhook payload truncation cap for non-failed events — design §11.3.
_WEBHOOK_TRUNCATE_BYTES = 512


def _truncate_for_webhook(text: Optional[str], cap: int = _WEBHOOK_TRUNCATE_BYTES) -> str:
    if not text:
        return ""
    if len(text) <= cap:
        return text
    return text[:cap] + "…(truncated)"


@dataclass
class ExecutionMetadata:
    """Durable record of one ResilientExecutor.execute() run.

    Phase 3 lands this dataclass + the conversion helpers; the
    executor accumulates retry_decisions / fallback_decisions during
    chain walk and constructs the metadata at terminal exit. The
    api-side wiring (commit 7) feeds an instance into RL +
    webhook_emitter closures.
    """

    run_id: str
    tenant_id: str
    user_id: Optional[str]
    decision_point: str
    platform_attempted: list[str]
    final_platform: Optional[str]
    attempt_count: int
    status: Status
    retry_decisions: list[FallbackDecision] = field(default_factory=list)
    fallback_decisions: list[FallbackDecision] = field(default_factory=list)
    duration_ms: int = 0
    workflow_id: Optional[str] = None
    activity_id: Optional[str] = None
    parent_task_id: Optional[str] = None
    stdout_summary: str = ""
    stderr_summary: str = ""
    exit_code: Optional[int] = None
    actionable_hint: Optional[str] = None
    tokens_in: Optional[int] = None
    tokens_out: Optional[int] = None
    cost_usd: Optional[float] = None

    # ── Constructor from ExecutionResult ─────────────────────────────

    @classmethod
    def from_execution_result(
        cls,
        *,
        result: ExecutionResult,
        tenant_id: str,
        user_id: Optional[str],
        decision_point: str,
        duration_ms: int,
        retry_decisions: Optional[list[FallbackDecision]] = None,
        fallback_decisions: Optional[list[FallbackDecision]] = None,
        parent_task_id: Optional[str] = None,
    ) -> "ExecutionMetadata":
        meta = result.metadata or {}
        return cls(
            run_id=result.run_id or "",
            tenant_id=tenant_id,
            user_id=user_id,
            decision_point=decision_point,
            platform_attempted=list(result.platform_attempted),
            final_platform=(
                result.platform if result.status is Status.EXECUTION_SUCCEEDED else None
            ),
            attempt_count=result.attempt_count,
            status=result.status,
            retry_decisions=list(retry_decisions or []),
            fallback_decisions=list(fallback_decisions or []),
            duration_ms=int(duration_ms),
            workflow_id=result.workflow_id,
            activity_id=result.activity_id,
            parent_task_id=parent_task_id,
            stdout_summary=result.stdout_summary or "",
            stderr_summary=result.stderr_summary or "",
            exit_code=result.exit_code,
            actionable_hint=result.actionable_hint,
            tokens_in=meta.get("tokens_in") if isinstance(meta, dict) else None,
            tokens_out=meta.get("tokens_out") if isinstance(meta, dict) else None,
            cost_usd=meta.get("cost_usd") if isinstance(meta, dict) else None,
        )

    # ── RL state / action shapes ─────────────────────────────────────

    def to_rl_experience_state(self) -> dict[str, Any]:
        """Lands in ``RLExperience.state`` (JSONB).

        Stable keys — the RL policy engine + dashboard read these.
        """
        return {
            "decision_point": self.decision_point,
            "platform_attempted": list(self.platform_attempted),
            "attempt_count": self.attempt_count,
            "duration_ms": self.duration_ms,
            "retry_count": len(self.retry_decisions),
            "fallback_count": len(self.fallback_decisions),
            "stderr_summary": self.stderr_summary,
            "exit_code": self.exit_code,
        }

    def to_rl_experience_action(self) -> dict[str, Any]:
        """Lands in ``RLExperience.action`` (JSONB).

        The "what we did" half — final_platform + actionable_hint
        + the chain we walked.
        """
        return {
            "final_platform": self.final_platform,
            "status": self.status.value,
            "actionable_hint": self.actionable_hint,
            "platform_chain": list(self.platform_attempted),
            "tokens_in": self.tokens_in,
            "tokens_out": self.tokens_out,
            "cost_usd": self.cost_usd,
            "workflow_id": self.workflow_id,
            "activity_id": self.activity_id,
        }

    def to_state_text(self) -> str:
        """Produce the embedded state_text the RL writer feeds into the
        embedding model. Plain-text summary, redaction-safe (the inputs
        are already redacted at the executor boundary)."""
        parts = [
            f"decision_point={self.decision_point}",
            f"chain={','.join(self.platform_attempted)}",
            f"status={self.status.value}",
            f"attempts={self.attempt_count}",
            f"duration_ms={self.duration_ms}",
        ]
        if self.actionable_hint:
            parts.append(f"hint={self.actionable_hint}")
        return " | ".join(parts)

    # ── Webhook payload shapes ───────────────────────────────────────

    def to_webhook_payload(self, event_type: str) -> dict[str, Any]:
        """Build the JSON-able outbound webhook payload.

        Design §11.3 specifies the keys per event type. Truncation:
        ``execution.failed`` gets the full 4KB redacted summary; all
        other events get the 512B cap to keep webhook traffic small.
        """
        is_failed = event_type == "execution.failed"
        truncate = (lambda s: s) if is_failed else _truncate_for_webhook
        base = {
            "run_id": self.run_id,
            "tenant_id": self.tenant_id,
            "decision_point": self.decision_point,
            "parent_task_id": self.parent_task_id,
            "status": self.status.value,
            "platform_attempted": list(self.platform_attempted),
            "platform_chain": list(self.platform_attempted),
            "attempt_count": self.attempt_count,
            "duration_ms": self.duration_ms,
            "actionable_hint": self.actionable_hint,
            "workflow_id": self.workflow_id,
            "activity_id": self.activity_id,
            "stdout_summary": truncate(self.stdout_summary),
            "stderr_summary": truncate(self.stderr_summary),
            "exit_code": self.exit_code,
            "tokens_in": self.tokens_in,
            "tokens_out": self.tokens_out,
            "cost_usd": self.cost_usd,
            "final_platform": self.final_platform,
        }
        return base


__all__ = ["ExecutionMetadata"]
